version: '3.9'
services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - "8081:8081"

  reservation-service:
    build: ./reservation-service
    container_name: reservation-service
    env_file:
      - ./reservation-service/.env
    ports:
      - "8082:8082"

  payment-service:
    build: ./payment-service
    container_name: payment-service
    env_file:
      - ./payment-service/.env
    ports:
      - "8083:8083"
